/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Embroidery Factory Management SaaS API
 * OpenAPI spec version: 0.1.0
 */
import { apiMutator } from '../../apps/web/lib/api-mutator';
export interface AccessTokenResponse {
  access_token: string;
  token_type?: string;
}

export interface EffectivePermissionsResponse {
  user_id: string;
  is_super_admin: boolean;
  permissions: string[];
}

export interface ForgotPasswordRequest {
  email: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export type LoginRequestTotpCode = string | null;

export interface LoginRequest {
  email: string;
  password: string;
  totp_code?: LoginRequestTotpCode;
}

export type PartyCreateRequestContactPerson = string | null;

export type PartyCreateRequestPhone = string | null;

export type PartyCreateRequestEmail = string | null;

export type PartyCreateRequestAddress = string | null;

export type PartyCreateRequestCity = string | null;

export type PartyCreateRequestTaxId = string | null;

export type PartyCreateRequestOpeningBalance = number | string;

export type PartyCreateRequestNotes = string | null;

export interface PartyCreateRequest {
  name: string;
  contact_person?: PartyCreateRequestContactPerson;
  phone?: PartyCreateRequestPhone;
  email?: PartyCreateRequestEmail;
  address?: PartyCreateRequestAddress;
  city?: PartyCreateRequestCity;
  tax_id?: PartyCreateRequestTaxId;
  opening_balance?: PartyCreateRequestOpeningBalance;
  notes?: PartyCreateRequestNotes;
}

export type PartyDocsOutContactPerson = string | null;

export type PartyDocsOutPhone = string | null;

export type PartyDocsOutEmail = string | null;

export type PartyDocsOutAddress = string | null;

export type PartyDocsOutCity = string | null;

export type PartyDocsOutTaxId = string | null;

export type PartyDocsOutNotes = string | null;

export type PartyDocsOutOpeningBalance = string | null;

/**
 * OpenAPI-documentation-only schema for GET/POST/PATCH /parties responses.

NOT passed to response_model anywhere and NOT used with .model_validate()
-- routers/parties.py's _serialize() still returns a PartyOut or
PartyWithBalanceOut instance directly, unvalidated against this class.
This exists solely to be referenced inside `responses={...}` dicts, which
injects a schema into openapi.json for docs/codegen (e.g. orval) without
FastAPI performing any response validation/filtering step -- that only
happens when response_model is set, which is deliberately not the case
here (see _serialize()'s docstring for why).

opening_balance is OPTIONAL here (unlike PartyWithBalanceOut, where it's
required) because whether the key is present on the wire depends on the
caller's parties.see_money permission at request time -- OpenAPI's static
schema format can't express that conditional, so "optional" is the
closest accurate approximation.
 */
export interface PartyDocsOut {
  id: string;
  name: string;
  contact_person: PartyDocsOutContactPerson;
  phone: PartyDocsOutPhone;
  email: PartyDocsOutEmail;
  address: PartyDocsOutAddress;
  city: PartyDocsOutCity;
  tax_id: PartyDocsOutTaxId;
  notes: PartyDocsOutNotes;
  is_active: boolean;
  opening_balance?: PartyDocsOutOpeningBalance;
}

export type PartyUpdateRequestName = string | null;

export type PartyUpdateRequestContactPerson = string | null;

export type PartyUpdateRequestPhone = string | null;

export type PartyUpdateRequestEmail = string | null;

export type PartyUpdateRequestAddress = string | null;

export type PartyUpdateRequestCity = string | null;

export type PartyUpdateRequestTaxId = string | null;

export type PartyUpdateRequestOpeningBalance = number | string | null;

export type PartyUpdateRequestNotes = string | null;

export type PartyUpdateRequestIsActive = boolean | null;

export interface PartyUpdateRequest {
  name?: PartyUpdateRequestName;
  contact_person?: PartyUpdateRequestContactPerson;
  phone?: PartyUpdateRequestPhone;
  email?: PartyUpdateRequestEmail;
  address?: PartyUpdateRequestAddress;
  city?: PartyUpdateRequestCity;
  tax_id?: PartyUpdateRequestTaxId;
  opening_balance?: PartyUpdateRequestOpeningBalance;
  notes?: PartyUpdateRequestNotes;
  is_active?: PartyUpdateRequestIsActive;
}

export interface PermissionOut {
  id: string;
  code: string;
  description: string;
}

export type PermissionOverrideRequestEffect = 'grant' | 'deny' | null;

export interface PermissionOverrideRequest {
  permission_code: string;
  effect?: PermissionOverrideRequestEffect;
}

export interface RefreshRequest {
  refresh_token: string;
}

export interface ResetPasswordRequest {
  token: string;
  new_password: string;
}

export interface RoleCreateRequest {
  name: string;
  permission_codes?: string[];
}

export interface RoleOut {
  id: string;
  name: string;
  is_template: boolean;
  permissions: PermissionOut[];
}

export type RoleUpdateRequestName = string | null;

export type RoleUpdateRequestPermissionCodes = string[] | null;

export interface RoleUpdateRequest {
  name?: RoleUpdateRequestName;
  permission_codes?: RoleUpdateRequestPermissionCodes;
}

export type SupplierCreateRequestContactPerson = string | null;

export type SupplierCreateRequestPhone = string | null;

export type SupplierCreateRequestEmail = string | null;

export type SupplierCreateRequestAddress = string | null;

export type SupplierCreateRequestCity = string | null;

export type SupplierCreateRequestTaxId = string | null;

export type SupplierCreateRequestOpeningBalance = number | string;

export type SupplierCreateRequestNotes = string | null;

export interface SupplierCreateRequest {
  name: string;
  contact_person?: SupplierCreateRequestContactPerson;
  phone?: SupplierCreateRequestPhone;
  email?: SupplierCreateRequestEmail;
  address?: SupplierCreateRequestAddress;
  city?: SupplierCreateRequestCity;
  tax_id?: SupplierCreateRequestTaxId;
  opening_balance?: SupplierCreateRequestOpeningBalance;
  notes?: SupplierCreateRequestNotes;
}

export type SupplierDocsOutContactPerson = string | null;

export type SupplierDocsOutPhone = string | null;

export type SupplierDocsOutEmail = string | null;

export type SupplierDocsOutAddress = string | null;

export type SupplierDocsOutCity = string | null;

export type SupplierDocsOutTaxId = string | null;

export type SupplierDocsOutNotes = string | null;

export type SupplierDocsOutOpeningBalance = string | null;

/**
 * OpenAPI-documentation-only schema for GET/POST/PATCH /suppliers
responses -- same reasoning as PartyDocsOut in schemas/party.py. Not used
for response_model or .model_validate(), only inside `responses={...}`.
 */
export interface SupplierDocsOut {
  id: string;
  name: string;
  contact_person: SupplierDocsOutContactPerson;
  phone: SupplierDocsOutPhone;
  email: SupplierDocsOutEmail;
  address: SupplierDocsOutAddress;
  city: SupplierDocsOutCity;
  tax_id: SupplierDocsOutTaxId;
  notes: SupplierDocsOutNotes;
  is_active: boolean;
  opening_balance?: SupplierDocsOutOpeningBalance;
}

export type SupplierUpdateRequestName = string | null;

export type SupplierUpdateRequestContactPerson = string | null;

export type SupplierUpdateRequestPhone = string | null;

export type SupplierUpdateRequestEmail = string | null;

export type SupplierUpdateRequestAddress = string | null;

export type SupplierUpdateRequestCity = string | null;

export type SupplierUpdateRequestTaxId = string | null;

export type SupplierUpdateRequestOpeningBalance = number | string | null;

export type SupplierUpdateRequestNotes = string | null;

export type SupplierUpdateRequestIsActive = boolean | null;

export interface SupplierUpdateRequest {
  name?: SupplierUpdateRequestName;
  contact_person?: SupplierUpdateRequestContactPerson;
  phone?: SupplierUpdateRequestPhone;
  email?: SupplierUpdateRequestEmail;
  address?: SupplierUpdateRequestAddress;
  city?: SupplierUpdateRequestCity;
  tax_id?: SupplierUpdateRequestTaxId;
  opening_balance?: SupplierUpdateRequestOpeningBalance;
  notes?: SupplierUpdateRequestNotes;
  is_active?: SupplierUpdateRequestIsActive;
}

export interface TokenResponse {
  access_token: string;
  refresh_token: string;
  token_type?: string;
}

export interface TotpDisableRequest {
  password: string;
}

export interface TotpSetupResponse {
  secret: string;
  provisioning_uri: string;
}

export interface TotpVerifyRequest {
  secret: string;
  code: string;
}

export interface UserProfileResponse {
  id: string;
  tenant_id: string;
  email: string;
  full_name: string;
  is_super_admin: boolean;
  is_platform_admin: boolean;
  mfa_enabled: boolean;
}

export type ValidationErrorLocItem = string | number;

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export type HealthHealthGet200 = { [key: string]: unknown };

export type ForgotPassword200 = { [key: string]: unknown };

export type ResetPassword200 = { [key: string]: unknown };

export type VerifyTotp200 = { [key: string]: unknown };

export type DisableTotp200 = { [key: string]: unknown };

export type AssignRole200 = { [key: string]: unknown };

export type UnassignRole200 = { [key: string]: unknown };

export type ListPartiesParams = {
/**
 * @minimum 0
 */
skip?: number;
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
is_active?: boolean;
name?: string | null;
};

export type ListSuppliersParams = {
/**
 * @minimum 0
 */
skip?: number;
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
is_active?: boolean;
name?: string | null;
};

/**
 * @summary Health
 */
export const getHealthHealthGetUrl = () => {


  

  return `/health`
}

export const healthHealthGet = async ( options?: RequestInit): Promise<HealthHealthGet200> => {
  
  return apiMutator<HealthHealthGet200>(getHealthHealthGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Login
 */
export const getLoginUrl = () => {


  

  return `/auth/login`
}

export const login = async (loginRequest: LoginRequest, options?: RequestInit): Promise<TokenResponse> => {
  
  return apiMutator<TokenResponse>(getLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginRequest,)
  }
);}



/**
 * @summary Refresh
 */
export const getRefreshTokenUrl = () => {


  

  return `/auth/refresh`
}

export const refreshToken = async (refreshRequest: RefreshRequest, options?: RequestInit): Promise<AccessTokenResponse> => {
  
  return apiMutator<AccessTokenResponse>(getRefreshTokenUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      refreshRequest,)
  }
);}



/**
 * @summary Forgot Password
 */
export const getForgotPasswordUrl = () => {


  

  return `/auth/forgot-password`
}

export const forgotPassword = async (forgotPasswordRequest: ForgotPasswordRequest, options?: RequestInit): Promise<ForgotPassword200> => {
  
  return apiMutator<ForgotPassword200>(getForgotPasswordUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      forgotPasswordRequest,)
  }
);}



/**
 * @summary Reset Password
 */
export const getResetPasswordUrl = () => {


  

  return `/auth/reset-password`
}

export const resetPassword = async (resetPasswordRequest: ResetPasswordRequest, options?: RequestInit): Promise<ResetPassword200> => {
  
  return apiMutator<ResetPassword200>(getResetPasswordUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      resetPasswordRequest,)
  }
);}



/**
 * @summary Setup Totp
 */
export const getSetupTotpUrl = () => {


  

  return `/auth/2fa/setup`
}

export const setupTotp = async ( options?: RequestInit): Promise<TotpSetupResponse> => {
  
  return apiMutator<TotpSetupResponse>(getSetupTotpUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}



/**
 * @summary Verify Totp
 */
export const getVerifyTotpUrl = () => {


  

  return `/auth/2fa/verify`
}

export const verifyTotp = async (totpVerifyRequest: TotpVerifyRequest, options?: RequestInit): Promise<VerifyTotp200> => {
  
  return apiMutator<VerifyTotp200>(getVerifyTotpUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      totpVerifyRequest,)
  }
);}



/**
 * @summary Disable Totp
 */
export const getDisableTotpUrl = () => {


  

  return `/auth/2fa/disable`
}

export const disableTotp = async (totpDisableRequest: TotpDisableRequest, options?: RequestInit): Promise<DisableTotp200> => {
  
  return apiMutator<DisableTotp200>(getDisableTotpUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      totpDisableRequest,)
  }
);}



/**
 * @summary Me
 */
export const getGetMeUrl = () => {


  

  return `/auth/me`
}

export const getMe = async ( options?: RequestInit): Promise<UserProfileResponse> => {
  
  return apiMutator<UserProfileResponse>(getGetMeUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary List Permissions
 */
export const getListPermissionsUrl = () => {


  

  return `/permissions`
}

export const listPermissions = async ( options?: RequestInit): Promise<PermissionOut[]> => {
  
  return apiMutator<PermissionOut[]>(getListPermissionsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary List Roles
 */
export const getListRolesUrl = () => {


  

  return `/roles`
}

export const listRoles = async ( options?: RequestInit): Promise<RoleOut[]> => {
  
  return apiMutator<RoleOut[]>(getListRolesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Create Role
 */
export const getCreateRoleUrl = () => {


  

  return `/roles`
}

export const createRole = async (roleCreateRequest: RoleCreateRequest, options?: RequestInit): Promise<RoleOut> => {
  
  return apiMutator<RoleOut>(getCreateRoleUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      roleCreateRequest,)
  }
);}



/**
 * @summary Get Role
 */
export const getGetRoleUrl = (roleId: string,) => {


  

  return `/roles/${roleId}`
}

export const getRole = async (roleId: string, options?: RequestInit): Promise<RoleOut> => {
  
  return apiMutator<RoleOut>(getGetRoleUrl(roleId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Update Role
 */
export const getUpdateRoleUrl = (roleId: string,) => {


  

  return `/roles/${roleId}`
}

export const updateRole = async (roleId: string,
    roleUpdateRequest: RoleUpdateRequest, options?: RequestInit): Promise<RoleOut> => {
  
  return apiMutator<RoleOut>(getUpdateRoleUrl(roleId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      roleUpdateRequest,)
  }
);}



/**
 * @summary Assign Role
 */
export const getAssignRoleUrl = (userId: string,
    roleId: string,) => {


  

  return `/users/${userId}/roles/${roleId}`
}

export const assignRole = async (userId: string,
    roleId: string, options?: RequestInit): Promise<AssignRole200> => {
  
  return apiMutator<AssignRole200>(getAssignRoleUrl(userId,roleId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}



/**
 * @summary Unassign Role
 */
export const getUnassignRoleUrl = (userId: string,
    roleId: string,) => {


  

  return `/users/${userId}/roles/${roleId}`
}

export const unassignRole = async (userId: string,
    roleId: string, options?: RequestInit): Promise<UnassignRole200> => {
  
  return apiMutator<UnassignRole200>(getUnassignRoleUrl(userId,roleId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}



/**
 * @summary Get User Permissions
 */
export const getGetUserPermissionsUrl = (userId: string,) => {


  

  return `/users/${userId}/permissions`
}

export const getUserPermissions = async (userId: string, options?: RequestInit): Promise<EffectivePermissionsResponse> => {
  
  return apiMutator<EffectivePermissionsResponse>(getGetUserPermissionsUrl(userId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Set Permission Override
 */
export const getSetPermissionOverrideUrl = (userId: string,) => {


  

  return `/users/${userId}/permission-overrides`
}

export const setPermissionOverride = async (userId: string,
    permissionOverrideRequest: PermissionOverrideRequest, options?: RequestInit): Promise<EffectivePermissionsResponse> => {
  
  return apiMutator<EffectivePermissionsResponse>(getSetPermissionOverrideUrl(userId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      permissionOverrideRequest,)
  }
);}



/**
 * @summary Get My Permissions
 */
export const getGetMyPermissionsUrl = () => {


  

  return `/me/permissions`
}

export const getMyPermissions = async ( options?: RequestInit): Promise<EffectivePermissionsResponse> => {
  
  return apiMutator<EffectivePermissionsResponse>(getGetMyPermissionsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary List Parties
 */
export const getListPartiesUrl = (params?: ListPartiesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/parties?${stringifiedParams}` : `/parties`
}

export const listParties = async (params?: ListPartiesParams, options?: RequestInit): Promise<PartyDocsOut[]> => {
  
  return apiMutator<PartyDocsOut[]>(getListPartiesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Create Party
 */
export const getCreatePartyUrl = () => {


  

  return `/parties`
}

export const createParty = async (partyCreateRequest: PartyCreateRequest, options?: RequestInit): Promise<PartyDocsOut> => {
  
  return apiMutator<PartyDocsOut>(getCreatePartyUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      partyCreateRequest,)
  }
);}



/**
 * @summary Get Party
 */
export const getGetPartyUrl = (partyId: string,) => {


  

  return `/parties/${partyId}`
}

export const getParty = async (partyId: string, options?: RequestInit): Promise<PartyDocsOut> => {
  
  return apiMutator<PartyDocsOut>(getGetPartyUrl(partyId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Update Party
 */
export const getUpdatePartyUrl = (partyId: string,) => {


  

  return `/parties/${partyId}`
}

export const updateParty = async (partyId: string,
    partyUpdateRequest: PartyUpdateRequest, options?: RequestInit): Promise<PartyDocsOut> => {
  
  return apiMutator<PartyDocsOut>(getUpdatePartyUrl(partyId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      partyUpdateRequest,)
  }
);}



/**
 * @summary List Suppliers
 */
export const getListSuppliersUrl = (params?: ListSuppliersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/suppliers?${stringifiedParams}` : `/suppliers`
}

export const listSuppliers = async (params?: ListSuppliersParams, options?: RequestInit): Promise<SupplierDocsOut[]> => {
  
  return apiMutator<SupplierDocsOut[]>(getListSuppliersUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Create Supplier
 */
export const getCreateSupplierUrl = () => {


  

  return `/suppliers`
}

export const createSupplier = async (supplierCreateRequest: SupplierCreateRequest, options?: RequestInit): Promise<SupplierDocsOut> => {
  
  return apiMutator<SupplierDocsOut>(getCreateSupplierUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      supplierCreateRequest,)
  }
);}



/**
 * @summary Get Supplier
 */
export const getGetSupplierUrl = (supplierId: string,) => {


  

  return `/suppliers/${supplierId}`
}

export const getSupplier = async (supplierId: string, options?: RequestInit): Promise<SupplierDocsOut> => {
  
  return apiMutator<SupplierDocsOut>(getGetSupplierUrl(supplierId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Update Supplier
 */
export const getUpdateSupplierUrl = (supplierId: string,) => {


  

  return `/suppliers/${supplierId}`
}

export const updateSupplier = async (supplierId: string,
    supplierUpdateRequest: SupplierUpdateRequest, options?: RequestInit): Promise<SupplierDocsOut> => {
  
  return apiMutator<SupplierDocsOut>(getUpdateSupplierUrl(supplierId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      supplierUpdateRequest,)
  }
);}
