/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Embroidery Factory Management SaaS API
 * OpenAPI spec version: 0.1.0
 */
import { apiMutator } from '../../apps/web/lib/api-mutator';
export interface AccessTokenResponse {
  access_token: string;
  token_type?: string;
}

export type BranchCreateRequestAddress = string | null;

export type BranchCreateRequestCity = string | null;

export type BranchCreateRequestPhone = string | null;

export interface BranchCreateRequest {
  name: string;
  code: string;
  address?: BranchCreateRequestAddress;
  city?: BranchCreateRequestCity;
  phone?: BranchCreateRequestPhone;
  is_head_office?: boolean;
}

export type BranchOutAddress = string | null;

export type BranchOutCity = string | null;

export type BranchOutPhone = string | null;

export interface BranchOut {
  id: string;
  factory_id: string;
  name: string;
  code: string;
  address: BranchOutAddress;
  city: BranchOutCity;
  phone: BranchOutPhone;
  is_head_office: boolean;
  is_active: boolean;
}

export type BranchUpdateRequestName = string | null;

export type BranchUpdateRequestCode = string | null;

export type BranchUpdateRequestAddress = string | null;

export type BranchUpdateRequestCity = string | null;

export type BranchUpdateRequestPhone = string | null;

export type BranchUpdateRequestIsHeadOffice = boolean | null;

export type BranchUpdateRequestIsActive = boolean | null;

export interface BranchUpdateRequest {
  name?: BranchUpdateRequestName;
  code?: BranchUpdateRequestCode;
  address?: BranchUpdateRequestAddress;
  city?: BranchUpdateRequestCity;
  phone?: BranchUpdateRequestPhone;
  is_head_office?: BranchUpdateRequestIsHeadOffice;
  is_active?: BranchUpdateRequestIsActive;
}

export interface EffectivePermissionsResponse {
  user_id: string;
  is_super_admin: boolean;
  permissions: string[];
}

export type EmployeeCreateRequestUserId = string | null;

export type EmployeeCreateRequestDesignation = string | null;

export type EmployeeCreateRequestPhone = string | null;

export type EmployeeCreateRequestEmail = string | null;

export type EmployeeCreateRequestNationalId = string | null;

export type EmployeeCreateRequestHireDate = string | null;

export interface EmployeeCreateRequest {
  branch_id: string;
  user_id?: EmployeeCreateRequestUserId;
  employee_code: string;
  full_name: string;
  designation?: EmployeeCreateRequestDesignation;
  phone?: EmployeeCreateRequestPhone;
  email?: EmployeeCreateRequestEmail;
  national_id?: EmployeeCreateRequestNationalId;
  hire_date?: EmployeeCreateRequestHireDate;
  employment_status?: string;
}

export type EmployeeOutUserId = string | null;

export type EmployeeOutDesignation = string | null;

export type EmployeeOutPhone = string | null;

export type EmployeeOutEmail = string | null;

export type EmployeeOutNationalId = string | null;

export type EmployeeOutHireDate = string | null;

export interface EmployeeOut {
  id: string;
  branch_id: string;
  user_id: EmployeeOutUserId;
  employee_code: string;
  full_name: string;
  designation: EmployeeOutDesignation;
  phone: EmployeeOutPhone;
  email: EmployeeOutEmail;
  national_id: EmployeeOutNationalId;
  hire_date: EmployeeOutHireDate;
  employment_status: string;
  is_active: boolean;
}

export type EmployeeUpdateRequestEmployeeCode = string | null;

export type EmployeeUpdateRequestFullName = string | null;

export type EmployeeUpdateRequestDesignation = string | null;

export type EmployeeUpdateRequestPhone = string | null;

export type EmployeeUpdateRequestEmail = string | null;

export type EmployeeUpdateRequestNationalId = string | null;

export type EmployeeUpdateRequestHireDate = string | null;

export type EmployeeUpdateRequestEmploymentStatus = string | null;

export type EmployeeUpdateRequestIsActive = boolean | null;

export interface EmployeeUpdateRequest {
  employee_code?: EmployeeUpdateRequestEmployeeCode;
  full_name?: EmployeeUpdateRequestFullName;
  designation?: EmployeeUpdateRequestDesignation;
  phone?: EmployeeUpdateRequestPhone;
  email?: EmployeeUpdateRequestEmail;
  national_id?: EmployeeUpdateRequestNationalId;
  hire_date?: EmployeeUpdateRequestHireDate;
  employment_status?: EmployeeUpdateRequestEmploymentStatus;
  is_active?: EmployeeUpdateRequestIsActive;
}

export type FactoryCreateRequestLegalName = string | null;

export type FactoryCreateRequestAddressLine1 = string | null;

export type FactoryCreateRequestAddressLine2 = string | null;

export type FactoryCreateRequestCity = string | null;

export type FactoryCreateRequestState = string | null;

export type FactoryCreateRequestPostalCode = string | null;

export type FactoryCreateRequestPhone = string | null;

export type FactoryCreateRequestEmail = string | null;

export type FactoryCreateRequestTaxId = string | null;

export type FactoryCreateRequestLogoUrl = string | null;

export interface FactoryCreateRequest {
  name: string;
  legal_name?: FactoryCreateRequestLegalName;
  address_line1?: FactoryCreateRequestAddressLine1;
  address_line2?: FactoryCreateRequestAddressLine2;
  city?: FactoryCreateRequestCity;
  state?: FactoryCreateRequestState;
  postal_code?: FactoryCreateRequestPostalCode;
  country?: string;
  phone?: FactoryCreateRequestPhone;
  email?: FactoryCreateRequestEmail;
  tax_id?: FactoryCreateRequestTaxId;
  logo_url?: FactoryCreateRequestLogoUrl;
  currency?: string;
  fiscal_year_start_month?: number;
}

export type FactoryOutLegalName = string | null;

export type FactoryOutAddressLine1 = string | null;

export type FactoryOutAddressLine2 = string | null;

export type FactoryOutCity = string | null;

export type FactoryOutState = string | null;

export type FactoryOutPostalCode = string | null;

export type FactoryOutPhone = string | null;

export type FactoryOutEmail = string | null;

export type FactoryOutTaxId = string | null;

export type FactoryOutLogoUrl = string | null;

export interface FactoryOut {
  id: string;
  name: string;
  legal_name: FactoryOutLegalName;
  address_line1: FactoryOutAddressLine1;
  address_line2: FactoryOutAddressLine2;
  city: FactoryOutCity;
  state: FactoryOutState;
  postal_code: FactoryOutPostalCode;
  country: string;
  phone: FactoryOutPhone;
  email: FactoryOutEmail;
  tax_id: FactoryOutTaxId;
  logo_url: FactoryOutLogoUrl;
  currency: string;
  fiscal_year_start_month: number;
  is_active: boolean;
}

export type FactoryUpdateRequestName = string | null;

export type FactoryUpdateRequestLegalName = string | null;

export type FactoryUpdateRequestAddressLine1 = string | null;

export type FactoryUpdateRequestAddressLine2 = string | null;

export type FactoryUpdateRequestCity = string | null;

export type FactoryUpdateRequestState = string | null;

export type FactoryUpdateRequestPostalCode = string | null;

export type FactoryUpdateRequestCountry = string | null;

export type FactoryUpdateRequestPhone = string | null;

export type FactoryUpdateRequestEmail = string | null;

export type FactoryUpdateRequestTaxId = string | null;

export type FactoryUpdateRequestLogoUrl = string | null;

export type FactoryUpdateRequestCurrency = string | null;

export type FactoryUpdateRequestFiscalYearStartMonth = number | null;

export type FactoryUpdateRequestIsActive = boolean | null;

export interface FactoryUpdateRequest {
  name?: FactoryUpdateRequestName;
  legal_name?: FactoryUpdateRequestLegalName;
  address_line1?: FactoryUpdateRequestAddressLine1;
  address_line2?: FactoryUpdateRequestAddressLine2;
  city?: FactoryUpdateRequestCity;
  state?: FactoryUpdateRequestState;
  postal_code?: FactoryUpdateRequestPostalCode;
  country?: FactoryUpdateRequestCountry;
  phone?: FactoryUpdateRequestPhone;
  email?: FactoryUpdateRequestEmail;
  tax_id?: FactoryUpdateRequestTaxId;
  logo_url?: FactoryUpdateRequestLogoUrl;
  currency?: FactoryUpdateRequestCurrency;
  fiscal_year_start_month?: FactoryUpdateRequestFiscalYearStartMonth;
  is_active?: FactoryUpdateRequestIsActive;
}

export interface ForgotPasswordRequest {
  email: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export type LoginRequestTotpCode = string | null;

export interface LoginRequest {
  email: string;
  password: string;
  totp_code?: LoginRequestTotpCode;
}

export interface LotColourCreateRequest {
  colour_name: string;
  suit_count: number;
}

export interface LotColourOut {
  id: string;
  lot_id: string;
  colour_name: string;
  suit_count: number;
}

export interface LotColourWithComponentsOut {
  id: string;
  lot_id: string;
  colour_name: string;
  suit_count: number;
  components: LotComponentOut[];
}

export interface LotComponentConfirmRequest {
  confirmed_quantity: number;
}

export type LotComponentOutConfirmedQuantity = number | null;

export interface LotComponentOut {
  id: string;
  lot_colour_id: string;
  component_type: string;
  expected_quantity: number;
  confirmed_quantity: LotComponentOutConfirmedQuantity;
  is_confirmed: boolean;
}

export type LotCreateRequestSuitType = typeof LotCreateRequestSuitType[keyof typeof LotCreateRequestSuitType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LotCreateRequestSuitType = {
  one_piece: 'one_piece',
  two_piece: 'two_piece',
  three_piece: 'three_piece',
} as const;

export type LotCreateRequestNotes = string | null;

export interface LotCreateRequest {
  branch_id: string;
  party_id: string;
  received_date: string;
  suit_type: LotCreateRequestSuitType;
  total_suit_count: number;
  notes?: LotCreateRequestNotes;
}

export type LotDetailOutNotes = string | null;

/**
 * Used by GET /lots/{id}, generate-components, and confirm -- built
manually by the router (no ORM relationships defined on Lot/LotColour),
not derived automatically from response_model attribute access.
 */
export interface LotDetailOut {
  id: string;
  branch_id: string;
  party_id: string;
  lot_number: string;
  received_date: string;
  suit_type: string;
  total_suit_count: number;
  status: string;
  notes: LotDetailOutNotes;
  colours: LotColourWithComponentsOut[];
}

export type LotOutNotes = string | null;

export interface LotOut {
  id: string;
  branch_id: string;
  party_id: string;
  lot_number: string;
  received_date: string;
  suit_type: string;
  total_suit_count: number;
  status: string;
  notes: LotOutNotes;
}

export type LotUpdateRequestBranchId = string | null;

export type LotUpdateRequestPartyId = string | null;

export type LotUpdateRequestReceivedDate = string | null;

export type LotUpdateRequestSuitType = 'one_piece' | 'two_piece' | 'three_piece' | null;

export type LotUpdateRequestTotalSuitCount = number | null;

export type LotUpdateRequestNotes = string | null;

export interface LotUpdateRequest {
  branch_id?: LotUpdateRequestBranchId;
  party_id?: LotUpdateRequestPartyId;
  received_date?: LotUpdateRequestReceivedDate;
  suit_type?: LotUpdateRequestSuitType;
  total_suit_count?: LotUpdateRequestTotalSuitCount;
  notes?: LotUpdateRequestNotes;
}

export type MachineCreateRequestName = string | null;

export type MachineCreateRequestMachineType = string | null;

export type MachineCreateRequestNumberOfHeads = number | null;

export type MachineCreateRequestBrand = string | null;

export type MachineCreateRequestModel = string | null;

export type MachineCreateRequestPurchaseDate = string | null;

export type MachineCreateRequestNotes = string | null;

export interface MachineCreateRequest {
  branch_id: string;
  code: string;
  name?: MachineCreateRequestName;
  machine_type?: MachineCreateRequestMachineType;
  number_of_heads?: MachineCreateRequestNumberOfHeads;
  brand?: MachineCreateRequestBrand;
  model?: MachineCreateRequestModel;
  purchase_date?: MachineCreateRequestPurchaseDate;
  status?: string;
  notes?: MachineCreateRequestNotes;
}

export type MachineOutName = string | null;

export type MachineOutMachineType = string | null;

export type MachineOutNumberOfHeads = number | null;

export type MachineOutBrand = string | null;

export type MachineOutModel = string | null;

export type MachineOutPurchaseDate = string | null;

export type MachineOutNotes = string | null;

export interface MachineOut {
  id: string;
  branch_id: string;
  code: string;
  name: MachineOutName;
  machine_type: MachineOutMachineType;
  number_of_heads: MachineOutNumberOfHeads;
  brand: MachineOutBrand;
  model: MachineOutModel;
  purchase_date: MachineOutPurchaseDate;
  status: string;
  notes: MachineOutNotes;
  is_active: boolean;
}

export type MachineUpdateRequestCode = string | null;

export type MachineUpdateRequestName = string | null;

export type MachineUpdateRequestMachineType = string | null;

export type MachineUpdateRequestNumberOfHeads = number | null;

export type MachineUpdateRequestBrand = string | null;

export type MachineUpdateRequestModel = string | null;

export type MachineUpdateRequestPurchaseDate = string | null;

export type MachineUpdateRequestStatus = string | null;

export type MachineUpdateRequestNotes = string | null;

export type MachineUpdateRequestIsActive = boolean | null;

export interface MachineUpdateRequest {
  code?: MachineUpdateRequestCode;
  name?: MachineUpdateRequestName;
  machine_type?: MachineUpdateRequestMachineType;
  number_of_heads?: MachineUpdateRequestNumberOfHeads;
  brand?: MachineUpdateRequestBrand;
  model?: MachineUpdateRequestModel;
  purchase_date?: MachineUpdateRequestPurchaseDate;
  status?: MachineUpdateRequestStatus;
  notes?: MachineUpdateRequestNotes;
  is_active?: MachineUpdateRequestIsActive;
}

export type PartyCreateRequestContactPerson = string | null;

export type PartyCreateRequestPhone = string | null;

export type PartyCreateRequestEmail = string | null;

export type PartyCreateRequestAddress = string | null;

export type PartyCreateRequestCity = string | null;

export type PartyCreateRequestTaxId = string | null;

export type PartyCreateRequestOpeningBalance = number | string;

export type PartyCreateRequestNotes = string | null;

export interface PartyCreateRequest {
  name: string;
  contact_person?: PartyCreateRequestContactPerson;
  phone?: PartyCreateRequestPhone;
  email?: PartyCreateRequestEmail;
  address?: PartyCreateRequestAddress;
  city?: PartyCreateRequestCity;
  tax_id?: PartyCreateRequestTaxId;
  opening_balance?: PartyCreateRequestOpeningBalance;
  notes?: PartyCreateRequestNotes;
}

export type PartyDocsOutContactPerson = string | null;

export type PartyDocsOutPhone = string | null;

export type PartyDocsOutEmail = string | null;

export type PartyDocsOutAddress = string | null;

export type PartyDocsOutCity = string | null;

export type PartyDocsOutTaxId = string | null;

export type PartyDocsOutNotes = string | null;

export type PartyDocsOutOpeningBalance = string | null;

/**
 * OpenAPI-documentation-only schema for GET/POST/PATCH /parties responses.

NOT passed to response_model anywhere and NOT used with .model_validate()
-- routers/parties.py's _serialize() still returns a PartyOut or
PartyWithBalanceOut instance directly, unvalidated against this class.
This exists solely to be referenced inside `responses={...}` dicts, which
injects a schema into openapi.json for docs/codegen (e.g. orval) without
FastAPI performing any response validation/filtering step -- that only
happens when response_model is set, which is deliberately not the case
here (see _serialize()'s docstring for why).

opening_balance is OPTIONAL here (unlike PartyWithBalanceOut, where it's
required) because whether the key is present on the wire depends on the
caller's parties.see_money permission at request time -- OpenAPI's static
schema format can't express that conditional, so "optional" is the
closest accurate approximation.
 */
export interface PartyDocsOut {
  id: string;
  name: string;
  contact_person: PartyDocsOutContactPerson;
  phone: PartyDocsOutPhone;
  email: PartyDocsOutEmail;
  address: PartyDocsOutAddress;
  city: PartyDocsOutCity;
  tax_id: PartyDocsOutTaxId;
  notes: PartyDocsOutNotes;
  is_active: boolean;
  opening_balance?: PartyDocsOutOpeningBalance;
}

export type PartyUpdateRequestName = string | null;

export type PartyUpdateRequestContactPerson = string | null;

export type PartyUpdateRequestPhone = string | null;

export type PartyUpdateRequestEmail = string | null;

export type PartyUpdateRequestAddress = string | null;

export type PartyUpdateRequestCity = string | null;

export type PartyUpdateRequestTaxId = string | null;

export type PartyUpdateRequestOpeningBalance = number | string | null;

export type PartyUpdateRequestNotes = string | null;

export type PartyUpdateRequestIsActive = boolean | null;

export interface PartyUpdateRequest {
  name?: PartyUpdateRequestName;
  contact_person?: PartyUpdateRequestContactPerson;
  phone?: PartyUpdateRequestPhone;
  email?: PartyUpdateRequestEmail;
  address?: PartyUpdateRequestAddress;
  city?: PartyUpdateRequestCity;
  tax_id?: PartyUpdateRequestTaxId;
  opening_balance?: PartyUpdateRequestOpeningBalance;
  notes?: PartyUpdateRequestNotes;
  is_active?: PartyUpdateRequestIsActive;
}

export interface PermissionOut {
  id: string;
  code: string;
  description: string;
}

export type PermissionOverrideRequestEffect = 'grant' | 'deny' | null;

export interface PermissionOverrideRequest {
  permission_code: string;
  effect?: PermissionOverrideRequestEffect;
}

export interface RefreshRequest {
  refresh_token: string;
}

export interface ResetPasswordRequest {
  token: string;
  new_password: string;
}

export interface RoleCreateRequest {
  name: string;
  permission_codes?: string[];
}

export interface RoleOut {
  id: string;
  name: string;
  is_template: boolean;
  permissions: PermissionOut[];
}

export type RoleUpdateRequestName = string | null;

export type RoleUpdateRequestPermissionCodes = string[] | null;

export interface RoleUpdateRequest {
  name?: RoleUpdateRequestName;
  permission_codes?: RoleUpdateRequestPermissionCodes;
}

export type SupplierCreateRequestContactPerson = string | null;

export type SupplierCreateRequestPhone = string | null;

export type SupplierCreateRequestEmail = string | null;

export type SupplierCreateRequestAddress = string | null;

export type SupplierCreateRequestCity = string | null;

export type SupplierCreateRequestTaxId = string | null;

export type SupplierCreateRequestOpeningBalance = number | string;

export type SupplierCreateRequestNotes = string | null;

export interface SupplierCreateRequest {
  name: string;
  contact_person?: SupplierCreateRequestContactPerson;
  phone?: SupplierCreateRequestPhone;
  email?: SupplierCreateRequestEmail;
  address?: SupplierCreateRequestAddress;
  city?: SupplierCreateRequestCity;
  tax_id?: SupplierCreateRequestTaxId;
  opening_balance?: SupplierCreateRequestOpeningBalance;
  notes?: SupplierCreateRequestNotes;
}

export type SupplierDocsOutContactPerson = string | null;

export type SupplierDocsOutPhone = string | null;

export type SupplierDocsOutEmail = string | null;

export type SupplierDocsOutAddress = string | null;

export type SupplierDocsOutCity = string | null;

export type SupplierDocsOutTaxId = string | null;

export type SupplierDocsOutNotes = string | null;

export type SupplierDocsOutOpeningBalance = string | null;

/**
 * OpenAPI-documentation-only schema for GET/POST/PATCH /suppliers
responses -- same reasoning as PartyDocsOut in schemas/party.py. Not used
for response_model or .model_validate(), only inside `responses={...}`.
 */
export interface SupplierDocsOut {
  id: string;
  name: string;
  contact_person: SupplierDocsOutContactPerson;
  phone: SupplierDocsOutPhone;
  email: SupplierDocsOutEmail;
  address: SupplierDocsOutAddress;
  city: SupplierDocsOutCity;
  tax_id: SupplierDocsOutTaxId;
  notes: SupplierDocsOutNotes;
  is_active: boolean;
  opening_balance?: SupplierDocsOutOpeningBalance;
}

export type SupplierUpdateRequestName = string | null;

export type SupplierUpdateRequestContactPerson = string | null;

export type SupplierUpdateRequestPhone = string | null;

export type SupplierUpdateRequestEmail = string | null;

export type SupplierUpdateRequestAddress = string | null;

export type SupplierUpdateRequestCity = string | null;

export type SupplierUpdateRequestTaxId = string | null;

export type SupplierUpdateRequestOpeningBalance = number | string | null;

export type SupplierUpdateRequestNotes = string | null;

export type SupplierUpdateRequestIsActive = boolean | null;

export interface SupplierUpdateRequest {
  name?: SupplierUpdateRequestName;
  contact_person?: SupplierUpdateRequestContactPerson;
  phone?: SupplierUpdateRequestPhone;
  email?: SupplierUpdateRequestEmail;
  address?: SupplierUpdateRequestAddress;
  city?: SupplierUpdateRequestCity;
  tax_id?: SupplierUpdateRequestTaxId;
  opening_balance?: SupplierUpdateRequestOpeningBalance;
  notes?: SupplierUpdateRequestNotes;
  is_active?: SupplierUpdateRequestIsActive;
}

export interface TokenResponse {
  access_token: string;
  refresh_token: string;
  token_type?: string;
}

export interface TotpDisableRequest {
  password: string;
}

export interface TotpSetupResponse {
  secret: string;
  provisioning_uri: string;
}

export interface TotpVerifyRequest {
  secret: string;
  code: string;
}

export interface UserProfileResponse {
  id: string;
  tenant_id: string;
  email: string;
  full_name: string;
  is_super_admin: boolean;
  is_platform_admin: boolean;
  mfa_enabled: boolean;
}

export type ValidationErrorLocItem = string | number;

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export type HealthHealthGet200 = { [key: string]: unknown };

export type ForgotPassword200 = { [key: string]: unknown };

export type ResetPassword200 = { [key: string]: unknown };

export type VerifyTotp200 = { [key: string]: unknown };

export type DisableTotp200 = { [key: string]: unknown };

export type AssignRole200 = { [key: string]: unknown };

export type UnassignRole200 = { [key: string]: unknown };

export type ListBranchesParams = {
/**
 * @minimum 0
 */
skip?: number;
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
is_active?: boolean;
name?: string | null;
};

export type ListMachinesParams = {
/**
 * @minimum 0
 */
skip?: number;
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
is_active?: boolean;
code?: string | null;
branch_id?: string | null;
};

export type ListEmployeesParams = {
/**
 * @minimum 0
 */
skip?: number;
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
is_active?: boolean;
full_name?: string | null;
branch_id?: string | null;
};

export type ListPartiesParams = {
/**
 * @minimum 0
 */
skip?: number;
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
is_active?: boolean;
name?: string | null;
};

export type ListSuppliersParams = {
/**
 * @minimum 0
 */
skip?: number;
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
is_active?: boolean;
name?: string | null;
};

export type ListLotsParams = {
/**
 * @minimum 0
 */
skip?: number;
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
party_id?: string | null;
status?: string | null;
};

/**
 * @summary Health
 */
export const getHealthHealthGetUrl = () => {


  

  return `/health`
}

export const healthHealthGet = async ( options?: RequestInit): Promise<HealthHealthGet200> => {
  
  return apiMutator<HealthHealthGet200>(getHealthHealthGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Login
 */
export const getLoginUrl = () => {


  

  return `/auth/login`
}

export const login = async (loginRequest: LoginRequest, options?: RequestInit): Promise<TokenResponse> => {
  
  return apiMutator<TokenResponse>(getLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginRequest,)
  }
);}



/**
 * @summary Refresh
 */
export const getRefreshTokenUrl = () => {


  

  return `/auth/refresh`
}

export const refreshToken = async (refreshRequest: RefreshRequest, options?: RequestInit): Promise<AccessTokenResponse> => {
  
  return apiMutator<AccessTokenResponse>(getRefreshTokenUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      refreshRequest,)
  }
);}



/**
 * @summary Forgot Password
 */
export const getForgotPasswordUrl = () => {


  

  return `/auth/forgot-password`
}

export const forgotPassword = async (forgotPasswordRequest: ForgotPasswordRequest, options?: RequestInit): Promise<ForgotPassword200> => {
  
  return apiMutator<ForgotPassword200>(getForgotPasswordUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      forgotPasswordRequest,)
  }
);}



/**
 * @summary Reset Password
 */
export const getResetPasswordUrl = () => {


  

  return `/auth/reset-password`
}

export const resetPassword = async (resetPasswordRequest: ResetPasswordRequest, options?: RequestInit): Promise<ResetPassword200> => {
  
  return apiMutator<ResetPassword200>(getResetPasswordUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      resetPasswordRequest,)
  }
);}



/**
 * @summary Setup Totp
 */
export const getSetupTotpUrl = () => {


  

  return `/auth/2fa/setup`
}

export const setupTotp = async ( options?: RequestInit): Promise<TotpSetupResponse> => {
  
  return apiMutator<TotpSetupResponse>(getSetupTotpUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}



/**
 * @summary Verify Totp
 */
export const getVerifyTotpUrl = () => {


  

  return `/auth/2fa/verify`
}

export const verifyTotp = async (totpVerifyRequest: TotpVerifyRequest, options?: RequestInit): Promise<VerifyTotp200> => {
  
  return apiMutator<VerifyTotp200>(getVerifyTotpUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      totpVerifyRequest,)
  }
);}



/**
 * @summary Disable Totp
 */
export const getDisableTotpUrl = () => {


  

  return `/auth/2fa/disable`
}

export const disableTotp = async (totpDisableRequest: TotpDisableRequest, options?: RequestInit): Promise<DisableTotp200> => {
  
  return apiMutator<DisableTotp200>(getDisableTotpUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      totpDisableRequest,)
  }
);}



/**
 * @summary Me
 */
export const getGetMeUrl = () => {


  

  return `/auth/me`
}

export const getMe = async ( options?: RequestInit): Promise<UserProfileResponse> => {
  
  return apiMutator<UserProfileResponse>(getGetMeUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary List Permissions
 */
export const getListPermissionsUrl = () => {


  

  return `/permissions`
}

export const listPermissions = async ( options?: RequestInit): Promise<PermissionOut[]> => {
  
  return apiMutator<PermissionOut[]>(getListPermissionsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary List Roles
 */
export const getListRolesUrl = () => {


  

  return `/roles`
}

export const listRoles = async ( options?: RequestInit): Promise<RoleOut[]> => {
  
  return apiMutator<RoleOut[]>(getListRolesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Create Role
 */
export const getCreateRoleUrl = () => {


  

  return `/roles`
}

export const createRole = async (roleCreateRequest: RoleCreateRequest, options?: RequestInit): Promise<RoleOut> => {
  
  return apiMutator<RoleOut>(getCreateRoleUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      roleCreateRequest,)
  }
);}



/**
 * @summary Get Role
 */
export const getGetRoleUrl = (roleId: string,) => {


  

  return `/roles/${roleId}`
}

export const getRole = async (roleId: string, options?: RequestInit): Promise<RoleOut> => {
  
  return apiMutator<RoleOut>(getGetRoleUrl(roleId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Update Role
 */
export const getUpdateRoleUrl = (roleId: string,) => {


  

  return `/roles/${roleId}`
}

export const updateRole = async (roleId: string,
    roleUpdateRequest: RoleUpdateRequest, options?: RequestInit): Promise<RoleOut> => {
  
  return apiMutator<RoleOut>(getUpdateRoleUrl(roleId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      roleUpdateRequest,)
  }
);}



/**
 * @summary Assign Role
 */
export const getAssignRoleUrl = (userId: string,
    roleId: string,) => {


  

  return `/users/${userId}/roles/${roleId}`
}

export const assignRole = async (userId: string,
    roleId: string, options?: RequestInit): Promise<AssignRole200> => {
  
  return apiMutator<AssignRole200>(getAssignRoleUrl(userId,roleId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}



/**
 * @summary Unassign Role
 */
export const getUnassignRoleUrl = (userId: string,
    roleId: string,) => {


  

  return `/users/${userId}/roles/${roleId}`
}

export const unassignRole = async (userId: string,
    roleId: string, options?: RequestInit): Promise<UnassignRole200> => {
  
  return apiMutator<UnassignRole200>(getUnassignRoleUrl(userId,roleId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}



/**
 * @summary Get User Permissions
 */
export const getGetUserPermissionsUrl = (userId: string,) => {


  

  return `/users/${userId}/permissions`
}

export const getUserPermissions = async (userId: string, options?: RequestInit): Promise<EffectivePermissionsResponse> => {
  
  return apiMutator<EffectivePermissionsResponse>(getGetUserPermissionsUrl(userId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Set Permission Override
 */
export const getSetPermissionOverrideUrl = (userId: string,) => {


  

  return `/users/${userId}/permission-overrides`
}

export const setPermissionOverride = async (userId: string,
    permissionOverrideRequest: PermissionOverrideRequest, options?: RequestInit): Promise<EffectivePermissionsResponse> => {
  
  return apiMutator<EffectivePermissionsResponse>(getSetPermissionOverrideUrl(userId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      permissionOverrideRequest,)
  }
);}



/**
 * @summary Get My Permissions
 */
export const getGetMyPermissionsUrl = () => {


  

  return `/me/permissions`
}

export const getMyPermissions = async ( options?: RequestInit): Promise<EffectivePermissionsResponse> => {
  
  return apiMutator<EffectivePermissionsResponse>(getGetMyPermissionsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Get Factory
 */
export const getGetFactoryUrl = () => {


  

  return `/factory`
}

export const getFactory = async ( options?: RequestInit): Promise<FactoryOut> => {
  
  return apiMutator<FactoryOut>(getGetFactoryUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Create Factory
 */
export const getCreateFactoryUrl = () => {


  

  return `/factory`
}

export const createFactory = async (factoryCreateRequest: FactoryCreateRequest, options?: RequestInit): Promise<FactoryOut> => {
  
  return apiMutator<FactoryOut>(getCreateFactoryUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      factoryCreateRequest,)
  }
);}



/**
 * @summary Update Factory
 */
export const getUpdateFactoryUrl = () => {


  

  return `/factory`
}

export const updateFactory = async (factoryUpdateRequest: FactoryUpdateRequest, options?: RequestInit): Promise<FactoryOut> => {
  
  return apiMutator<FactoryOut>(getUpdateFactoryUrl(),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      factoryUpdateRequest,)
  }
);}



/**
 * @summary List Branches
 */
export const getListBranchesUrl = (params?: ListBranchesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/branches?${stringifiedParams}` : `/branches`
}

export const listBranches = async (params?: ListBranchesParams, options?: RequestInit): Promise<BranchOut[]> => {
  
  return apiMutator<BranchOut[]>(getListBranchesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Create Branch
 */
export const getCreateBranchUrl = () => {


  

  return `/branches`
}

export const createBranch = async (branchCreateRequest: BranchCreateRequest, options?: RequestInit): Promise<BranchOut> => {
  
  return apiMutator<BranchOut>(getCreateBranchUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      branchCreateRequest,)
  }
);}



/**
 * @summary Get Branch
 */
export const getGetBranchUrl = (branchId: string,) => {


  

  return `/branches/${branchId}`
}

export const getBranch = async (branchId: string, options?: RequestInit): Promise<BranchOut> => {
  
  return apiMutator<BranchOut>(getGetBranchUrl(branchId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Update Branch
 */
export const getUpdateBranchUrl = (branchId: string,) => {


  

  return `/branches/${branchId}`
}

export const updateBranch = async (branchId: string,
    branchUpdateRequest: BranchUpdateRequest, options?: RequestInit): Promise<BranchOut> => {
  
  return apiMutator<BranchOut>(getUpdateBranchUrl(branchId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      branchUpdateRequest,)
  }
);}



/**
 * @summary List Machines
 */
export const getListMachinesUrl = (params?: ListMachinesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/machines?${stringifiedParams}` : `/machines`
}

export const listMachines = async (params?: ListMachinesParams, options?: RequestInit): Promise<MachineOut[]> => {
  
  return apiMutator<MachineOut[]>(getListMachinesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Create Machine
 */
export const getCreateMachineUrl = () => {


  

  return `/machines`
}

export const createMachine = async (machineCreateRequest: MachineCreateRequest, options?: RequestInit): Promise<MachineOut> => {
  
  return apiMutator<MachineOut>(getCreateMachineUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      machineCreateRequest,)
  }
);}



/**
 * @summary Get Machine
 */
export const getGetMachineUrl = (machineId: string,) => {


  

  return `/machines/${machineId}`
}

export const getMachine = async (machineId: string, options?: RequestInit): Promise<MachineOut> => {
  
  return apiMutator<MachineOut>(getGetMachineUrl(machineId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Update Machine
 */
export const getUpdateMachineUrl = (machineId: string,) => {


  

  return `/machines/${machineId}`
}

export const updateMachine = async (machineId: string,
    machineUpdateRequest: MachineUpdateRequest, options?: RequestInit): Promise<MachineOut> => {
  
  return apiMutator<MachineOut>(getUpdateMachineUrl(machineId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      machineUpdateRequest,)
  }
);}



/**
 * @summary List Employees
 */
export const getListEmployeesUrl = (params?: ListEmployeesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/employees?${stringifiedParams}` : `/employees`
}

export const listEmployees = async (params?: ListEmployeesParams, options?: RequestInit): Promise<EmployeeOut[]> => {
  
  return apiMutator<EmployeeOut[]>(getListEmployeesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Create Employee
 */
export const getCreateEmployeeUrl = () => {


  

  return `/employees`
}

export const createEmployee = async (employeeCreateRequest: EmployeeCreateRequest, options?: RequestInit): Promise<EmployeeOut> => {
  
  return apiMutator<EmployeeOut>(getCreateEmployeeUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      employeeCreateRequest,)
  }
);}



/**
 * @summary Get Employee
 */
export const getGetEmployeeUrl = (employeeId: string,) => {


  

  return `/employees/${employeeId}`
}

export const getEmployee = async (employeeId: string, options?: RequestInit): Promise<EmployeeOut> => {
  
  return apiMutator<EmployeeOut>(getGetEmployeeUrl(employeeId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Update Employee
 */
export const getUpdateEmployeeUrl = (employeeId: string,) => {


  

  return `/employees/${employeeId}`
}

export const updateEmployee = async (employeeId: string,
    employeeUpdateRequest: EmployeeUpdateRequest, options?: RequestInit): Promise<EmployeeOut> => {
  
  return apiMutator<EmployeeOut>(getUpdateEmployeeUrl(employeeId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      employeeUpdateRequest,)
  }
);}



/**
 * @summary List Parties
 */
export const getListPartiesUrl = (params?: ListPartiesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/parties?${stringifiedParams}` : `/parties`
}

export const listParties = async (params?: ListPartiesParams, options?: RequestInit): Promise<PartyDocsOut[]> => {
  
  return apiMutator<PartyDocsOut[]>(getListPartiesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Create Party
 */
export const getCreatePartyUrl = () => {


  

  return `/parties`
}

export const createParty = async (partyCreateRequest: PartyCreateRequest, options?: RequestInit): Promise<PartyDocsOut> => {
  
  return apiMutator<PartyDocsOut>(getCreatePartyUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      partyCreateRequest,)
  }
);}



/**
 * @summary Get Party
 */
export const getGetPartyUrl = (partyId: string,) => {


  

  return `/parties/${partyId}`
}

export const getParty = async (partyId: string, options?: RequestInit): Promise<PartyDocsOut> => {
  
  return apiMutator<PartyDocsOut>(getGetPartyUrl(partyId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Update Party
 */
export const getUpdatePartyUrl = (partyId: string,) => {


  

  return `/parties/${partyId}`
}

export const updateParty = async (partyId: string,
    partyUpdateRequest: PartyUpdateRequest, options?: RequestInit): Promise<PartyDocsOut> => {
  
  return apiMutator<PartyDocsOut>(getUpdatePartyUrl(partyId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      partyUpdateRequest,)
  }
);}



/**
 * @summary List Suppliers
 */
export const getListSuppliersUrl = (params?: ListSuppliersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/suppliers?${stringifiedParams}` : `/suppliers`
}

export const listSuppliers = async (params?: ListSuppliersParams, options?: RequestInit): Promise<SupplierDocsOut[]> => {
  
  return apiMutator<SupplierDocsOut[]>(getListSuppliersUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Create Supplier
 */
export const getCreateSupplierUrl = () => {


  

  return `/suppliers`
}

export const createSupplier = async (supplierCreateRequest: SupplierCreateRequest, options?: RequestInit): Promise<SupplierDocsOut> => {
  
  return apiMutator<SupplierDocsOut>(getCreateSupplierUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      supplierCreateRequest,)
  }
);}



/**
 * @summary Get Supplier
 */
export const getGetSupplierUrl = (supplierId: string,) => {


  

  return `/suppliers/${supplierId}`
}

export const getSupplier = async (supplierId: string, options?: RequestInit): Promise<SupplierDocsOut> => {
  
  return apiMutator<SupplierDocsOut>(getGetSupplierUrl(supplierId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Update Supplier
 */
export const getUpdateSupplierUrl = (supplierId: string,) => {


  

  return `/suppliers/${supplierId}`
}

export const updateSupplier = async (supplierId: string,
    supplierUpdateRequest: SupplierUpdateRequest, options?: RequestInit): Promise<SupplierDocsOut> => {
  
  return apiMutator<SupplierDocsOut>(getUpdateSupplierUrl(supplierId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      supplierUpdateRequest,)
  }
);}



/**
 * @summary List Lots
 */
export const getListLotsUrl = (params?: ListLotsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/lots?${stringifiedParams}` : `/lots`
}

export const listLots = async (params?: ListLotsParams, options?: RequestInit): Promise<LotOut[]> => {
  
  return apiMutator<LotOut[]>(getListLotsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Create Lot
 */
export const getCreateLotUrl = () => {


  

  return `/lots`
}

export const createLot = async (lotCreateRequest: LotCreateRequest, options?: RequestInit): Promise<LotOut> => {
  
  return apiMutator<LotOut>(getCreateLotUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      lotCreateRequest,)
  }
);}



/**
 * @summary Get Lot
 */
export const getGetLotUrl = (lotId: string,) => {


  

  return `/lots/${lotId}`
}

export const getLot = async (lotId: string, options?: RequestInit): Promise<LotDetailOut> => {
  
  return apiMutator<LotDetailOut>(getGetLotUrl(lotId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Update Lot
 */
export const getUpdateLotUrl = (lotId: string,) => {


  

  return `/lots/${lotId}`
}

export const updateLot = async (lotId: string,
    lotUpdateRequest: LotUpdateRequest, options?: RequestInit): Promise<LotOut> => {
  
  return apiMutator<LotOut>(getUpdateLotUrl(lotId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      lotUpdateRequest,)
  }
);}



/**
 * @summary Add Lot Colour
 */
export const getAddLotColourUrl = (lotId: string,) => {


  

  return `/lots/${lotId}/colours`
}

export const addLotColour = async (lotId: string,
    lotColourCreateRequest: LotColourCreateRequest, options?: RequestInit): Promise<LotColourOut> => {
  
  return apiMutator<LotColourOut>(getAddLotColourUrl(lotId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      lotColourCreateRequest,)
  }
);}



/**
 * @summary Remove Lot Colour
 */
export const getRemoveLotColourUrl = (lotId: string,
    colourId: string,) => {


  

  return `/lots/${lotId}/colours/${colourId}`
}

export const removeLotColour = async (lotId: string,
    colourId: string, options?: RequestInit): Promise<void> => {
  
  return apiMutator<void>(getRemoveLotColourUrl(lotId,colourId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}



/**
 * @summary Generate Lot Components
 */
export const getGenerateLotComponentsUrl = (lotId: string,) => {


  

  return `/lots/${lotId}/generate-components`
}

export const generateLotComponents = async (lotId: string, options?: RequestInit): Promise<LotDetailOut> => {
  
  return apiMutator<LotDetailOut>(getGenerateLotComponentsUrl(lotId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}



/**
 * @summary Confirm Lot Component
 */
export const getConfirmLotComponentUrl = (lotId: string,
    componentId: string,) => {


  

  return `/lots/${lotId}/components/${componentId}`
}

export const confirmLotComponent = async (lotId: string,
    componentId: string,
    lotComponentConfirmRequest: LotComponentConfirmRequest, options?: RequestInit): Promise<LotComponentOut> => {
  
  return apiMutator<LotComponentOut>(getConfirmLotComponentUrl(lotId,componentId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      lotComponentConfirmRequest,)
  }
);}



/**
 * @summary Confirm Lot
 */
export const getConfirmLotUrl = (lotId: string,) => {


  

  return `/lots/${lotId}/confirm`
}

export const confirmLot = async (lotId: string, options?: RequestInit): Promise<LotDetailOut> => {
  
  return apiMutator<LotDetailOut>(getConfirmLotUrl(lotId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}
