import uuid

from sqlalchemy import Boolean, CheckConstraint, ForeignKey, Integer, String, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base, TimestampMixin, UUIDPrimaryKeyMixin

COMPONENT_TYPES = ("front", "back", "sleeves", "trouser", "dupatta")

# Which component types generate per colour, keyed by Lot.suit_type.
# Scope doc §5.6: sleeves are always a pair-unit (never doubled); trouser
# only applies to three-piece suits; dupatta applies to two- and
# three-piece.
COMPONENTS_BY_SUIT_TYPE: dict[str, tuple[str, ...]] = {
    "one_piece": ("front", "back", "sleeves"),
    "two_piece": ("front", "back", "sleeves", "dupatta"),
    "three_piece": ("front", "back", "sleeves", "trouser", "dupatta"),
}


class LotComponent(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    """An embroidery-trackable piece (front/back/sleeves/trouser/dupatta)
    for one LotColour, auto-generated by generate-components based on the
    parent Lot's suit_type. expected_quantity comes from the colour's
    suit_count; confirmed_quantity is staff-entered during the Component
    Confirmation step."""

    __tablename__ = "lot_components"
    __table_args__ = (
        UniqueConstraint("lot_colour_id", "component_type", name="uq_lot_components_colour_type"),
        CheckConstraint(
            "component_type IN ('front', 'back', 'sleeves', 'trouser', 'dupatta')",
            name="ck_lot_components_type",
        ),
    )

    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id"), nullable=False, index=True)
    lot_colour_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("lot_colours.id"), nullable=False, index=True)
    component_type: Mapped[str] = mapped_column(String(20), nullable=False)
    expected_quantity: Mapped[int] = mapped_column(Integer, nullable=False)
    confirmed_quantity: Mapped[int | None] = mapped_column(Integer, nullable=True)
    is_confirmed: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
