"""lot receiving schema

Revision ID: 013e07b51b45
Revises: b69b75fdf221
Create Date: 2026-08-11 18:17:19.032780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '013e07b51b45'
down_revision: Union[str, None] = 'b69b75fdf221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lots',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('party_id', sa.UUID(), nullable=False),
    sa.Column('lot_number', sa.String(length=20), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('suit_type', sa.String(length=20), nullable=False),
    sa.Column('total_suit_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending_breakdown', 'pending_confirmation', 'confirmed')", name='ck_lots_status'),
    sa.CheckConstraint("suit_type IN ('one_piece', 'two_piece', 'three_piece')", name='ck_lots_suit_type'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'lot_number', name='uq_lots_tenant_lot_number')
    )
    op.create_index(op.f('ix_lots_tenant_id'), 'lots', ['tenant_id'], unique=False)
    op.create_table('lot_colours',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('lot_id', sa.UUID(), nullable=False),
    sa.Column('colour_name', sa.String(length=100), nullable=False),
    sa.Column('suit_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lot_colours_lot_id'), 'lot_colours', ['lot_id'], unique=False)
    op.create_index(op.f('ix_lot_colours_tenant_id'), 'lot_colours', ['tenant_id'], unique=False)
    op.create_table('lot_components',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('lot_colour_id', sa.UUID(), nullable=False),
    sa.Column('component_type', sa.String(length=20), nullable=False),
    sa.Column('expected_quantity', sa.Integer(), nullable=False),
    sa.Column('confirmed_quantity', sa.Integer(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("component_type IN ('front', 'back', 'sleeves', 'trouser', 'dupatta')", name='ck_lot_components_type'),
    sa.ForeignKeyConstraint(['lot_colour_id'], ['lot_colours.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_colour_id', 'component_type', name='uq_lot_components_colour_type')
    )
    op.create_index(op.f('ix_lot_components_lot_colour_id'), 'lot_components', ['lot_colour_id'], unique=False)
    op.create_index(op.f('ix_lot_components_tenant_id'), 'lot_components', ['tenant_id'], unique=False)
    # server_default backfills existing factory rows (this column is
    # NOT NULL); the model's Python-side default=1 covers new rows going
    # forward the same way, so the default is intentionally left in place
    # rather than dropped after backfill.
    op.add_column(
        'factories', sa.Column('next_lot_number', sa.Integer(), nullable=False, server_default='1')
    )
    # NOTE: autogenerate also proposed dropping ix_roles_tenant_id and
    # ix_users_tenant_id here -- both are real, intentionally-created
    # indexes from e650e40e66c3 (hand-written via op.create_index, not
    # reflected as index=True on the User/Role models), so this is a
    # known autogenerate false-positive. Deliberately not included.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('factories', 'next_lot_number')
    op.drop_index(op.f('ix_lot_components_tenant_id'), table_name='lot_components')
    op.drop_index(op.f('ix_lot_components_lot_colour_id'), table_name='lot_components')
    op.drop_table('lot_components')
    op.drop_index(op.f('ix_lot_colours_tenant_id'), table_name='lot_colours')
    op.drop_index(op.f('ix_lot_colours_lot_id'), table_name='lot_colours')
    op.drop_table('lot_colours')
    op.drop_index(op.f('ix_lots_tenant_id'), table_name='lots')
    op.drop_table('lots')
    # ### end Alembic commands ###
