"""supplier payment schema

Revision ID: 06809154bbdc
Revises: 7a9a57c4d3c1
Create Date: 2026-08-19 15:51:29.166554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '06809154bbdc'
down_revision: Union[str, None] = '7a9a57c4d3c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_payments',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('payment_number', sa.String(length=20), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("payment_method IN ('cash', 'bank_transfer', 'cheque', 'other')", name='ck_supplier_payments_method'),
    sa.CheckConstraint('amount > 0', name='ck_supplier_payments_amount_positive'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'payment_number', name='uq_supplier_payments_tenant_payment_number')
    )
    op.create_index(op.f('ix_supplier_payments_supplier_id'), 'supplier_payments', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_supplier_payments_tenant_id'), 'supplier_payments', ['tenant_id'], unique=False)
    op.create_table('supplier_payment_allocations',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('supplier_payment_id', sa.UUID(), nullable=False),
    sa.Column('allocation_type', sa.String(length=20), nullable=False),
    sa.Column('purchase_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("allocation_type IN ('purchase', 'general', 'advance', 'unallocated')", name='ck_supplier_payment_allocations_type'),
    sa.CheckConstraint('amount > 0', name='ck_supplier_payment_allocations_amount_positive'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.ForeignKeyConstraint(['supplier_payment_id'], ['supplier_payments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_payment_allocations_purchase_id'), 'supplier_payment_allocations', ['purchase_id'], unique=False)
    op.create_index(op.f('ix_supplier_payment_allocations_supplier_payment_id'), 'supplier_payment_allocations', ['supplier_payment_id'], unique=False)
    op.create_index(op.f('ix_supplier_payment_allocations_tenant_id'), 'supplier_payment_allocations', ['tenant_id'], unique=False)
    # server_default backfills existing factory rows (these columns are NOT
    # NULL); the model's Python-side defaults cover new rows going forward
    # the same way -- same reasoning as next_payment_number in
    # 2faf0f9749b2_payment_schema.py.
    op.add_column(
        'factories',
        sa.Column('next_supplier_payment_number', sa.Integer(), nullable=False, server_default='1'),
    )
    op.add_column(
        'factories',
        sa.Column('supplier_payment_number_prefix', sa.String(length=20), nullable=False, server_default='SPMT'),
    )
    # NOTE: autogenerate also proposed dropping ix_roles_tenant_id and
    # ix_users_tenant_id here -- both are real, intentionally-created
    # indexes from e650e40e66c3, same known autogenerate false-positive
    # already called out in 2faf0f9749b2_payment_schema.py. Deliberately
    # not included.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('factories', 'supplier_payment_number_prefix')
    op.drop_column('factories', 'next_supplier_payment_number')
    op.drop_index(op.f('ix_supplier_payment_allocations_tenant_id'), table_name='supplier_payment_allocations')
    op.drop_index(op.f('ix_supplier_payment_allocations_supplier_payment_id'), table_name='supplier_payment_allocations')
    op.drop_index(op.f('ix_supplier_payment_allocations_purchase_id'), table_name='supplier_payment_allocations')
    op.drop_table('supplier_payment_allocations')
    op.drop_index(op.f('ix_supplier_payments_tenant_id'), table_name='supplier_payments')
    op.drop_index(op.f('ix_supplier_payments_supplier_id'), table_name='supplier_payments')
    op.drop_table('supplier_payments')
    # ### end Alembic commands ###
