"""payroll schema

Revision ID: 5aab5b813c52
Revises: f4a6b9c2d5e8
Create Date: 2026-08-13 12:47:01.133790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5aab5b813c52'
down_revision: Union[str, None] = 'f4a6b9c2d5e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_runs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'approved')", name='ck_payroll_runs_status'),
    sa.CheckConstraint('month >= 1 AND month <= 12', name='ck_payroll_runs_month_range'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'branch_id', 'year', 'month', name='uq_payroll_runs_tenant_branch_period')
    )
    op.create_index(op.f('ix_payroll_runs_tenant_id'), 'payroll_runs', ['tenant_id'], unique=False)
    op.create_table('advances',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('advance_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_advances_amount_positive'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advances_employee_id'), 'advances', ['employee_id'], unique=False)
    op.create_index(op.f('ix_advances_tenant_id'), 'advances', ['tenant_id'], unique=False)
    op.create_table('bonuses',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('payroll_run_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_bonuses_amount_positive'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bonuses_employee_id'), 'bonuses', ['employee_id'], unique=False)
    op.create_index(op.f('ix_bonuses_payroll_run_id'), 'bonuses', ['payroll_run_id'], unique=False)
    op.create_index(op.f('ix_bonuses_tenant_id'), 'bonuses', ['tenant_id'], unique=False)
    op.create_table('deductions',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('payroll_run_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_deductions_amount_positive'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deductions_employee_id'), 'deductions', ['employee_id'], unique=False)
    op.create_index(op.f('ix_deductions_payroll_run_id'), 'deductions', ['payroll_run_id'], unique=False)
    op.create_index(op.f('ix_deductions_tenant_id'), 'deductions', ['tenant_id'], unique=False)
    op.create_table('employee_salary_profiles',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_salary_profiles_employee_id'), 'employee_salary_profiles', ['employee_id'], unique=True)
    op.create_index(op.f('ix_employee_salary_profiles_tenant_id'), 'employee_salary_profiles', ['tenant_id'], unique=False)
    op.create_table('payroll_entries',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('payroll_run_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payroll_run_id', 'employee_id', name='uq_payroll_entries_run_employee')
    )
    op.create_index(op.f('ix_payroll_entries_employee_id'), 'payroll_entries', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_entries_payroll_run_id'), 'payroll_entries', ['payroll_run_id'], unique=False)
    op.create_index(op.f('ix_payroll_entries_tenant_id'), 'payroll_entries', ['tenant_id'], unique=False)
    op.create_table('advance_installments',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('advance_id', sa.UUID(), nullable=False),
    sa.Column('payroll_run_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('installment_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_advance_installments_amount_positive'),
    sa.ForeignKeyConstraint(['advance_id'], ['advances.id'], ),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advance_installments_advance_id'), 'advance_installments', ['advance_id'], unique=False)
    op.create_index(op.f('ix_advance_installments_payroll_run_id'), 'advance_installments', ['payroll_run_id'], unique=False)
    op.create_index(op.f('ix_advance_installments_tenant_id'), 'advance_installments', ['tenant_id'], unique=False)
    # NOTE: autogenerate also proposed dropping ix_roles_tenant_id and
    # ix_users_tenant_id here -- both are real, intentionally-created
    # indexes from e650e40e66c3, same known autogenerate false-positive
    # already called out in 013e07b51b45_lot_receiving_schema.py.
    # Deliberately not included.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_advance_installments_tenant_id'), table_name='advance_installments')
    op.drop_index(op.f('ix_advance_installments_payroll_run_id'), table_name='advance_installments')
    op.drop_index(op.f('ix_advance_installments_advance_id'), table_name='advance_installments')
    op.drop_table('advance_installments')
    op.drop_index(op.f('ix_payroll_entries_tenant_id'), table_name='payroll_entries')
    op.drop_index(op.f('ix_payroll_entries_payroll_run_id'), table_name='payroll_entries')
    op.drop_index(op.f('ix_payroll_entries_employee_id'), table_name='payroll_entries')
    op.drop_table('payroll_entries')
    op.drop_index(op.f('ix_employee_salary_profiles_tenant_id'), table_name='employee_salary_profiles')
    op.drop_index(op.f('ix_employee_salary_profiles_employee_id'), table_name='employee_salary_profiles')
    op.drop_table('employee_salary_profiles')
    op.drop_index(op.f('ix_deductions_tenant_id'), table_name='deductions')
    op.drop_index(op.f('ix_deductions_payroll_run_id'), table_name='deductions')
    op.drop_index(op.f('ix_deductions_employee_id'), table_name='deductions')
    op.drop_table('deductions')
    op.drop_index(op.f('ix_bonuses_tenant_id'), table_name='bonuses')
    op.drop_index(op.f('ix_bonuses_payroll_run_id'), table_name='bonuses')
    op.drop_index(op.f('ix_bonuses_employee_id'), table_name='bonuses')
    op.drop_table('bonuses')
    op.drop_index(op.f('ix_advances_tenant_id'), table_name='advances')
    op.drop_index(op.f('ix_advances_employee_id'), table_name='advances')
    op.drop_table('advances')
    op.drop_index(op.f('ix_payroll_runs_tenant_id'), table_name='payroll_runs')
    op.drop_table('payroll_runs')
    # ### end Alembic commands ###
