"""add stitch count to design variant

Revision ID: 68fd3645463a
Revises: c4d8e1f6a9b3
Create Date: 2026-08-13 11:32:32.942821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '68fd3645463a'
down_revision: Union[str, None] = 'c4d8e1f6a9b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('design_variants', sa.Column('stitch_count', sa.Integer(), nullable=True))
    # NOTE: autogenerate also proposed dropping ix_roles_tenant_id and
    # ix_users_tenant_id here -- both are real, intentionally-created
    # indexes from e650e40e66c3, same known autogenerate false-positive
    # already called out in 013e07b51b45_lot_receiving_schema.py.
    # Deliberately not included.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('design_variants', 'stitch_count')
    # ### end Alembic commands ###
