"""machine current assignment fields

Revision ID: 722905027434
Revises: f17e2c966efa
Create Date: 2026-08-20 17:35:25.872044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '722905027434'
down_revision: Union[str, None] = 'f17e2c966efa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machines', sa.Column('current_shift', sa.String(length=20), nullable=True))
    op.add_column('machines', sa.Column('current_operator_employee_id', sa.UUID(), nullable=True))
    op.add_column('machines', sa.Column('current_helper_employee_id', sa.UUID(), nullable=True))
    op.add_column('machines', sa.Column('current_lot_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_machines_current_operator_employee_id', 'machines', 'employees',
        ['current_operator_employee_id'], ['id'],
    )
    op.create_foreign_key(
        'fk_machines_current_lot_id', 'machines', 'lots', ['current_lot_id'], ['id'],
    )
    op.create_foreign_key(
        'fk_machines_current_helper_employee_id', 'machines', 'employees',
        ['current_helper_employee_id'], ['id'],
    )
    # NOTE: autogenerate also proposed dropping ix_roles_tenant_id and
    # ix_users_tenant_id here -- both are real, intentionally-created
    # indexes from e650e40e66c3, same known autogenerate false-positive
    # already called out in 2faf0f9749b2_payment_schema.py. Deliberately
    # not included.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_machines_current_helper_employee_id', 'machines', type_='foreignkey')
    op.drop_constraint('fk_machines_current_lot_id', 'machines', type_='foreignkey')
    op.drop_constraint('fk_machines_current_operator_employee_id', 'machines', type_='foreignkey')
    op.drop_column('machines', 'current_lot_id')
    op.drop_column('machines', 'current_helper_employee_id')
    op.drop_column('machines', 'current_operator_employee_id')
    op.drop_column('machines', 'current_shift')
    # ### end Alembic commands ###
