"""tenant subscription fields

Revision ID: 7a9a57c4d3c1
Revises: a7bdc6a5c1fb
Create Date: 2026-08-17 13:34:31.218381

server_default matches each column's model-level Python default, same as
every other column added in a later migration -- existing Tenant rows need
a value for these new NOT NULL columns too. subscription_renews_at uses a
computed SQL default (today + 30 days) rather than a frozen literal so it
stays correct for rows inserted after this migration runs, matching the
model's lambda default.

NOTE: autogenerate proposed dropping ix_roles_tenant_id and
ix_users_tenant_id -- a known false positive, removed here same as every
prior schema migration in this repo.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7a9a57c4d3c1'
down_revision: Union[str, None] = 'a7bdc6a5c1fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'tenants', sa.Column('subscription_plan', sa.String(length=50), nullable=False, server_default='trial')
    )
    op.add_column(
        'tenants',
        sa.Column('subscription_status', sa.String(length=50), nullable=False, server_default='trialing'),
    )
    op.add_column(
        'tenants',
        sa.Column(
            'subscription_renews_at',
            sa.Date(),
            nullable=True,
            server_default=sa.text("(CURRENT_DATE + INTERVAL '30 days')"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'subscription_renews_at')
    op.drop_column('tenants', 'subscription_status')
    op.drop_column('tenants', 'subscription_plan')
    # ### end Alembic commands ###
