"""machine production entry schema

Revision ID: 7d5bbfd981cc
Revises: a1f3c9d4b2e7
Create Date: 2026-08-12 16:34:39.320722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7d5bbfd981cc'
down_revision: Union[str, None] = 'a1f3c9d4b2e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine_production_entries',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('production_job_machine_allocation_id', sa.UUID(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('shift', sa.String(length=20), nullable=False),
    sa.Column('operator_employee_id', sa.UUID(), nullable=False),
    sa.Column('helper_employee_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("shift IN ('morning', 'evening', 'night')", name='ck_production_entries_shift'),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='ck_production_entries_status'),
    sa.CheckConstraint('quantity > 0', name='ck_production_entries_quantity_positive'),
    sa.ForeignKeyConstraint(['helper_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['operator_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['production_job_machine_allocation_id'], ['production_job_machine_allocations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_production_entries_helper_employee_id'), 'machine_production_entries', ['helper_employee_id'], unique=False)
    op.create_index(op.f('ix_machine_production_entries_operator_employee_id'), 'machine_production_entries', ['operator_employee_id'], unique=False)
    op.create_index(op.f('ix_machine_production_entries_production_job_machine_allocation_id'), 'machine_production_entries', ['production_job_machine_allocation_id'], unique=False)
    op.create_index(op.f('ix_machine_production_entries_tenant_id'), 'machine_production_entries', ['tenant_id'], unique=False)
    # NOTE: autogenerate also proposed dropping ix_roles_tenant_id and
    # ix_users_tenant_id here -- both are real, intentionally-created
    # indexes from e650e40e66c3 (hand-written via op.create_index, not
    # reflected as index=True on the User/Role models), same known
    # autogenerate false-positive already called out in
    # 013e07b51b45_lot_receiving_schema.py. Deliberately not included.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_machine_production_entries_tenant_id'), table_name='machine_production_entries')
    op.drop_index(op.f('ix_machine_production_entries_production_job_machine_allocation_id'), table_name='machine_production_entries')
    op.drop_index(op.f('ix_machine_production_entries_operator_employee_id'), table_name='machine_production_entries')
    op.drop_index(op.f('ix_machine_production_entries_helper_employee_id'), table_name='machine_production_entries')
    op.drop_table('machine_production_entries')
    # ### end Alembic commands ###
