"""production job schema

Revision ID: 8861d5e6eb86
Revises: 2388c3e7c21a
Create Date: 2026-08-12 15:48:57.008717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8861d5e6eb86'
down_revision: Union[str, None] = '2388c3e7c21a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_jobs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('lot_colour_id', sa.UUID(), nullable=False),
    sa.Column('design_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'allocated')", name='ck_production_jobs_status'),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ),
    sa.ForeignKeyConstraint(['lot_colour_id'], ['lot_colours.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_colour_id', name='uq_production_jobs_lot_colour_id')
    )
    op.create_index(op.f('ix_production_jobs_design_id'), 'production_jobs', ['design_id'], unique=False)
    op.create_index(op.f('ix_production_jobs_lot_colour_id'), 'production_jobs', ['lot_colour_id'], unique=False)
    op.create_index(op.f('ix_production_jobs_tenant_id'), 'production_jobs', ['tenant_id'], unique=False)
    op.create_table('production_job_components',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('production_job_id', sa.UUID(), nullable=False),
    sa.Column('component_type', sa.String(length=20), nullable=False),
    sa.Column('target_quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("component_type IN ('front', 'back', 'sleeves', 'trouser', 'dupatta')", name='ck_production_job_components_type'),
    sa.ForeignKeyConstraint(['production_job_id'], ['production_jobs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('production_job_id', 'component_type', name='uq_production_job_components_job_type')
    )
    op.create_index(op.f('ix_production_job_components_production_job_id'), 'production_job_components', ['production_job_id'], unique=False)
    op.create_index(op.f('ix_production_job_components_tenant_id'), 'production_job_components', ['tenant_id'], unique=False)
    op.create_table('production_job_machine_allocations',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('production_job_component_id', sa.UUID(), nullable=False),
    sa.Column('machine_id', sa.UUID(), nullable=False),
    sa.Column('allocated_quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['production_job_component_id'], ['production_job_components.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('production_job_component_id', 'machine_id', name='uq_job_allocations_component_machine')
    )
    op.create_index(op.f('ix_production_job_machine_allocations_machine_id'), 'production_job_machine_allocations', ['machine_id'], unique=False)
    op.create_index(op.f('ix_production_job_machine_allocations_production_job_component_id'), 'production_job_machine_allocations', ['production_job_component_id'], unique=False)
    op.create_index(op.f('ix_production_job_machine_allocations_tenant_id'), 'production_job_machine_allocations', ['tenant_id'], unique=False)
    # NOTE: autogenerate also proposed dropping ix_roles_tenant_id and
    # ix_users_tenant_id here -- both are real, intentionally-created
    # indexes from e650e40e66c3 (hand-written via op.create_index, not
    # reflected as index=True on the User/Role models), same known
    # autogenerate false-positive already called out in
    # 013e07b51b45_lot_receiving_schema.py. Deliberately not included.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_job_machine_allocations_tenant_id'), table_name='production_job_machine_allocations')
    op.drop_index(op.f('ix_production_job_machine_allocations_production_job_component_id'), table_name='production_job_machine_allocations')
    op.drop_index(op.f('ix_production_job_machine_allocations_machine_id'), table_name='production_job_machine_allocations')
    op.drop_table('production_job_machine_allocations')
    op.drop_index(op.f('ix_production_job_components_tenant_id'), table_name='production_job_components')
    op.drop_index(op.f('ix_production_job_components_production_job_id'), table_name='production_job_components')
    op.drop_table('production_job_components')
    op.drop_index(op.f('ix_production_jobs_tenant_id'), table_name='production_jobs')
    op.drop_index(op.f('ix_production_jobs_lot_colour_id'), table_name='production_jobs')
    op.drop_index(op.f('ix_production_jobs_design_id'), table_name='production_jobs')
    op.drop_table('production_jobs')
    # ### end Alembic commands ###
