"""user permission overrides

Revision ID: 891756917d92
Revises: e650e40e66c3
Create Date: 2026-08-11 13:10:34.264145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '891756917d92'
down_revision: Union[str, None] = 'e650e40e66c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_permission_overrides',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('effect', sa.String(length=10), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("effect IN ('grant', 'deny')", name='ck_user_permission_override_effect'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'permission_id', name='uq_user_permission_override')
    )
    op.create_index(op.f('ix_user_permission_overrides_tenant_id'), 'user_permission_overrides', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_user_permission_overrides_user_id'), 'user_permission_overrides', ['user_id'], unique=False)
    # NOTE: autogenerate also flagged ix_roles_tenant_id/ix_users_tenant_id as
    # "removed" -- false positive. Those indexes were added via raw op.create_index
    # in e650e40e66c3 (RLS migration), not declared on the ORM model's tenant_id
    # column, so autogenerate sees model/DB drift and wants to drop them. Keep them.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_permission_overrides_user_id'), table_name='user_permission_overrides')
    op.drop_index(op.f('ix_user_permission_overrides_tenant_id'), table_name='user_permission_overrides')
    op.drop_table('user_permission_overrides')
    # ### end Alembic commands ###
