"""delivery challan schema

Revision ID: 8d7cc45f58d2
Revises: b6e2a0f7c9d1
Create Date: 2026-08-13 11:07:56.960660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8d7cc45f58d2'
down_revision: Union[str, None] = 'b6e2a0f7c9d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_challans',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('party_id', sa.UUID(), nullable=False),
    sa.Column('challan_number', sa.String(length=20), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'challan_number', name='uq_delivery_challans_tenant_challan_number')
    )
    op.create_index(op.f('ix_delivery_challans_party_id'), 'delivery_challans', ['party_id'], unique=False)
    op.create_index(op.f('ix_delivery_challans_tenant_id'), 'delivery_challans', ['tenant_id'], unique=False)
    op.create_table('delivery_challan_lines',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('delivery_challan_id', sa.UUID(), nullable=False),
    sa.Column('lot_colour_id', sa.UUID(), nullable=False),
    sa.Column('unit_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("unit_type IN ('shirt', 'dupatta', 'trouser')", name='ck_delivery_challan_lines_unit_type'),
    sa.CheckConstraint('quantity > 0', name='ck_delivery_challan_lines_quantity_positive'),
    sa.ForeignKeyConstraint(['delivery_challan_id'], ['delivery_challans.id'], ),
    sa.ForeignKeyConstraint(['lot_colour_id'], ['lot_colours.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_challan_lines_delivery_challan_id'), 'delivery_challan_lines', ['delivery_challan_id'], unique=False)
    op.create_index(op.f('ix_delivery_challan_lines_lot_colour_id'), 'delivery_challan_lines', ['lot_colour_id'], unique=False)
    op.create_index(op.f('ix_delivery_challan_lines_tenant_id'), 'delivery_challan_lines', ['tenant_id'], unique=False)
    # server_default backfills existing factory rows (this column is NOT
    # NULL); the model's Python-side default=1 covers new rows going
    # forward the same way, so the default is intentionally left in place
    # rather than dropped after backfill -- same reasoning as
    # next_lot_number in 013e07b51b45_lot_receiving_schema.py.
    op.add_column(
        'factories', sa.Column('next_challan_number', sa.Integer(), nullable=False, server_default='1')
    )
    # NOTE: autogenerate also proposed dropping ix_roles_tenant_id and
    # ix_users_tenant_id here -- both are real, intentionally-created
    # indexes from e650e40e66c3 (hand-written via op.create_index, not
    # reflected as index=True on the User/Role models), same known
    # autogenerate false-positive already called out in
    # 013e07b51b45_lot_receiving_schema.py. Deliberately not included.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('factories', 'next_challan_number')
    op.drop_index(op.f('ix_delivery_challan_lines_tenant_id'), table_name='delivery_challan_lines')
    op.drop_index(op.f('ix_delivery_challan_lines_lot_colour_id'), table_name='delivery_challan_lines')
    op.drop_index(op.f('ix_delivery_challan_lines_delivery_challan_id'), table_name='delivery_challan_lines')
    op.drop_table('delivery_challan_lines')
    op.drop_index(op.f('ix_delivery_challans_tenant_id'), table_name='delivery_challans')
    op.drop_index(op.f('ix_delivery_challans_party_id'), table_name='delivery_challans')
    op.drop_table('delivery_challans')
    # ### end Alembic commands ###
