"""purchase schema

Revision ID: 9ab732b31e45
Revises: a8c3f6e2b7d4
Create Date: 2026-08-13 12:05:50.740378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9ab732b31e45'
down_revision: Union[str, None] = 'a8c3f6e2b7d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchases',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('purchase_number', sa.String(length=20), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'purchase_number', name='uq_purchases_tenant_purchase_number')
    )
    op.create_index(op.f('ix_purchases_supplier_id'), 'purchases', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_purchases_tenant_id'), 'purchases', ['tenant_id'], unique=False)
    op.create_table('purchase_line_items',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('purchase_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_purchase_line_items_quantity_positive'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_line_items_purchase_id'), 'purchase_line_items', ['purchase_id'], unique=False)
    op.create_index(op.f('ix_purchase_line_items_tenant_id'), 'purchase_line_items', ['tenant_id'], unique=False)
    # server_default backfills existing factory rows (this column is NOT
    # NULL); the model's Python-side default=1 covers new rows going
    # forward the same way -- same reasoning as next_lot_number in
    # 013e07b51b45_lot_receiving_schema.py.
    op.add_column(
        'factories', sa.Column('next_purchase_number', sa.Integer(), nullable=False, server_default='1')
    )
    # NOTE: autogenerate also proposed dropping ix_roles_tenant_id and
    # ix_users_tenant_id here -- both are real, intentionally-created
    # indexes from e650e40e66c3, same known autogenerate false-positive
    # already called out in 013e07b51b45_lot_receiving_schema.py.
    # Deliberately not included.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('factories', 'next_purchase_number')
    op.drop_index(op.f('ix_purchase_line_items_tenant_id'), table_name='purchase_line_items')
    op.drop_index(op.f('ix_purchase_line_items_purchase_id'), table_name='purchase_line_items')
    op.drop_table('purchase_line_items')
    op.drop_index(op.f('ix_purchases_tenant_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_supplier_id'), table_name='purchases')
    op.drop_table('purchases')
    # ### end Alembic commands ###
