"""factory notification email settings

Revision ID: a7bdc6a5c1fb
Revises: d441645e8a43
Create Date: 2026-08-17 12:46:34.100003

server_default matches each column's model-level Python default, same as
every other Factory column added in a later migration -- existing Factory
rows need a value for these new NOT NULL columns too.

NOTE: autogenerate proposed dropping ix_roles_tenant_id and
ix_users_tenant_id -- a known false positive, removed here same as every
prior schema migration in this repo.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a7bdc6a5c1fb'
down_revision: Union[str, None] = 'd441645e8a43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'factories',
        sa.Column(
            'notification_from_name', sa.String(length=255), nullable=False, server_default='Embroidery SaaS'
        ),
    )
    op.add_column(
        'factories',
        sa.Column(
            'notification_from_email',
            sa.String(length=255),
            nullable=False,
            server_default='onboarding@resend.dev',
        ),
    )
    op.add_column('factories', sa.Column('notification_reply_to_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('factories', 'notification_reply_to_email')
    op.drop_column('factories', 'notification_from_email')
    op.drop_column('factories', 'notification_from_name')
    # ### end Alembic commands ###
