"""scheduled report settings schema

Revision ID: c02046852de3
Revises: c7d9a1e3f5b2
Create Date: 2026-08-13 15:58:30.897360

NOTE: autogenerate proposed dropping ix_roles_tenant_id and
ix_users_tenant_id -- a known false positive from an earlier migration's
manual index management, not a real diff. Removed from upgrade()/downgrade()
here, same as every prior schema migration in this repo.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c02046852de3'
down_revision: Union[str, None] = 'c7d9a1e3f5b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_report_settings',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('report_type', sa.String(length=30), nullable=False),
    sa.Column('frequency', sa.String(length=10), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("frequency IN ('weekly', 'monthly')", name='ck_scheduled_report_settings_frequency'),
    sa.CheckConstraint("report_type IN ('financial_summary')", name='ck_scheduled_report_settings_report_type'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_report_settings_tenant_id'), 'scheduled_report_settings', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_report_settings_tenant_id'), table_name='scheduled_report_settings')
    op.drop_table('scheduled_report_settings')
    # ### end Alembic commands ###
