"""factory document number prefixes

Revision ID: d441645e8a43
Revises: d4e8b2c6a9f1
Create Date: 2026-08-13 17:00:14.150996

server_default matches each column's model-level Python default, same as
every other Factory counter column added in a later migration -- existing
Factory rows need a value for these new NOT NULL columns too.

NOTE: autogenerate proposed dropping ix_roles_tenant_id and
ix_users_tenant_id -- a known false positive, removed here same as every
prior schema migration in this repo.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd441645e8a43'
down_revision: Union[str, None] = 'd4e8b2c6a9f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factories', sa.Column('lot_number_prefix', sa.String(length=20), nullable=False, server_default='LOT'))
    op.add_column('factories', sa.Column('challan_number_prefix', sa.String(length=20), nullable=False, server_default='CH'))
    op.add_column('factories', sa.Column('invoice_number_prefix', sa.String(length=20), nullable=False, server_default='INV'))
    op.add_column('factories', sa.Column('payment_number_prefix', sa.String(length=20), nullable=False, server_default='PMT'))
    op.add_column('factories', sa.Column('purchase_number_prefix', sa.String(length=20), nullable=False, server_default='PUR'))
    op.add_column('factories', sa.Column('expense_number_prefix', sa.String(length=20), nullable=False, server_default='EXP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('factories', 'expense_number_prefix')
    op.drop_column('factories', 'purchase_number_prefix')
    op.drop_column('factories', 'payment_number_prefix')
    op.drop_column('factories', 'invoice_number_prefix')
    op.drop_column('factories', 'challan_number_prefix')
    op.drop_column('factories', 'lot_number_prefix')
    # ### end Alembic commands ###
