"""design schema

Revision ID: d5ee464a035a
Revises: 9bcabe9dff2c
Create Date: 2026-08-11 19:00:31.919253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd5ee464a035a'
down_revision: Union[str, None] = '9bcabe9dff2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('designs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('master_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'master_number', name='uq_designs_tenant_master_number')
    )
    op.create_index(op.f('ix_designs_tenant_id'), 'designs', ['tenant_id'], unique=False)
    op.create_table('design_variants',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('design_id', sa.UUID(), nullable=False),
    sa.Column('component_type', sa.String(length=20), nullable=False),
    sa.Column('component_letter', sa.String(length=1), nullable=False),
    sa.Column('colour_variant_code', sa.String(length=50), nullable=False),
    sa.Column('variant_code', sa.String(length=80), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("component_type IN ('front', 'back', 'sleeves', 'trouser', 'dupatta')", name='ck_design_variants_component_type'),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('design_id', 'component_type', 'colour_variant_code', name='uq_design_variants_natural_key')
    )
    op.create_index(op.f('ix_design_variants_design_id'), 'design_variants', ['design_id'], unique=False)
    op.create_index(op.f('ix_design_variants_tenant_id'), 'design_variants', ['tenant_id'], unique=False)
    # NOTE: autogenerate also proposed dropping ix_roles_tenant_id and
    # ix_users_tenant_id here -- both are real, intentionally-created
    # indexes from e650e40e66c3 (hand-written via op.create_index, not
    # reflected as index=True on the User/Role models), so this is the
    # same known autogenerate false-positive seen in 013e07b51b45.
    # Deliberately not included.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_design_variants_tenant_id'), table_name='design_variants')
    op.drop_index(op.f('ix_design_variants_design_id'), table_name='design_variants')
    op.drop_table('design_variants')
    op.drop_index(op.f('ix_designs_tenant_id'), table_name='designs')
    op.drop_table('designs')
    # ### end Alembic commands ###
