"""purchase required and purchase line item inventory link

Revision ID: e0fd43de22a0
Revises: e9b2c5d8f1a3
Create Date: 2026-08-13 12:34:36.715035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e0fd43de22a0'
down_revision: Union[str, None] = 'e9b2c5d8f1a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_required',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_quantity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('purchase_required', 'pending_approval', 'approved', 'ordered', 'purchased', 'received')", name='ck_purchase_required_status'),
    sa.CheckConstraint('requested_quantity > 0', name='ck_purchase_required_quantity_positive'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_required_inventory_item_id'), 'purchase_required', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_purchase_required_tenant_id'), 'purchase_required', ['tenant_id'], unique=False)
    op.add_column('purchase_line_items', sa.Column('inventory_item_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_purchase_line_items_inventory_item_id'), 'purchase_line_items', ['inventory_item_id'], unique=False)
    # Named explicitly -- autogenerate proposed create_foreign_key(None, ...)
    # here, which names the constraint via Postgres's own default naming
    # convention at apply time; the matching drop_constraint(None, ...) in
    # downgrade() can't target that name (drop_constraint needs a real
    # name, not None), so this would silently fail if downgrade() were ever
    # actually run. Named it explicitly to close that gap.
    op.create_foreign_key(
        'fk_purchase_line_items_inventory_item_id', 'purchase_line_items', 'inventory_items',
        ['inventory_item_id'], ['id'],
    )
    # NOTE: autogenerate also proposed dropping ix_roles_tenant_id and
    # ix_users_tenant_id here -- both are real, intentionally-created
    # indexes from e650e40e66c3, same known autogenerate false-positive
    # already called out in 013e07b51b45_lot_receiving_schema.py.
    # Deliberately not included.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_purchase_line_items_inventory_item_id', 'purchase_line_items', type_='foreignkey')
    op.drop_index(op.f('ix_purchase_line_items_inventory_item_id'), table_name='purchase_line_items')
    op.drop_column('purchase_line_items', 'inventory_item_id')
    op.drop_index(op.f('ix_purchase_required_tenant_id'), table_name='purchase_required')
    op.drop_index(op.f('ix_purchase_required_inventory_item_id'), table_name='purchase_required')
    op.drop_table('purchase_required')
    # ### end Alembic commands ###
