"""production entry logged_by_user_id

Revision ID: f17e2c966efa
Revises: c2a4e6f8b1d3
Create Date: 2026-08-19 17:22:58.230500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f17e2c966efa'
down_revision: Union[str, None] = 'c2a4e6f8b1d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine_production_entries', sa.Column('logged_by_user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_machine_production_entries_logged_by_user_id'), 'machine_production_entries', ['logged_by_user_id'], unique=False)
    op.create_foreign_key(
        'fk_machine_production_entries_logged_by_user_id', 'machine_production_entries', 'users',
        ['logged_by_user_id'], ['id'],
    )
    # NOTE: autogenerate also proposed dropping ix_roles_tenant_id and
    # ix_users_tenant_id here -- both are real, intentionally-created
    # indexes from e650e40e66c3, same known autogenerate false-positive
    # already called out in 2faf0f9749b2_payment_schema.py. Deliberately
    # not included.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_machine_production_entries_logged_by_user_id', 'machine_production_entries', type_='foreignkey')
    op.drop_index(op.f('ix_machine_production_entries_logged_by_user_id'), table_name='machine_production_entries')
    op.drop_column('machine_production_entries', 'logged_by_user_id')
    # ### end Alembic commands ###
